Repository codestates-seb/seb43_main_032, pull requests merged in 2023-05, with the labels that each got.

#3 Feature/grid_box
  frontend/components/GridBox.tsx
Labels: feat, [FE]

#4 Feature/util date
  frontend/util/date/ elapsedTime.ts
  frontend/util/date/dateDiffInDays.ts
  frontend/util/date/formatDate.ts
Labels: feat, [FE]

#5 Feature/tag
  frontend/components/Tag.tsx
Labels: feat, [FE]

#12 Feature/skills sprites
  frontend/public/skills_sprites.png
  frontend/styles/App.css
  frontend/styles/skills.css
Labels: feat, [FE]

#13 style : margin-right 삭제
  frontend/components/Tag.tsx
Labels: feat, [FE]

#23 Feature/post btn
  frontend/components/MainPost.tsx
  frontend/components/PostBtn.tsx
  frontend/components/editor/Editor.tsx
  frontend/pages/project/create.tsx
Labels: feat, [FE]

#26 Feature/view project
  frontend/__mocks__/api.ts
  frontend/__mocks__/dummy/project.ts
  frontend/components/ContentBox.tsx
  frontend/components/Error.tsx
  frontend/components/GridBox.tsx
  frontend/components/Loading.tsx
  frontend/components/MainPost.tsx
  frontend/components/Tag.tsx
  frontend/components/editor/Editor.tsx
  frontend/components/project/PeriodBox.tsx
  frontend/components/project/StacksBox.tsx
  frontend/components/project/TagBox.tsx
  frontend/components/skeleton/ContentSkeleton.tsx
  frontend/components/skeleton/EiditorSkeleton.tsx
  frontend/components/skeleton/Skeleton.tsx
  frontend/components/stack/SelectedStacks.tsx
  frontend/hooks/react-query/useProject.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/project/[id]/index.tsx
  frontend/pages/project/create.tsx
  frontend/styles/App.css
  frontend/types/types.ts
  frontend/util/date/index.ts
Labels: feat, [FE]

#27 feat : btn
  frontend/components/Btn.tsx
Labels: feat, [FE]

#28 feat : _app Box
  frontend/pages/_app.tsx
Labels: feat, [FE]

#31 feat : JWT, Member 회원 가입, 로그인 구현
  backend/SideQuest/.gitignore
  backend/SideQuest/build.gradle
  backend/SideQuest/gradle/wrapper/gradle-wrapper.jar
  backend/SideQuest/gradle/wrapper/gradle-wrapper.properties
  backend/SideQuest/gradlew
  backend/SideQuest/gradlew.bat
  backend/SideQuest/settings.gradle
  backend/SideQuest/src/main/java/com/main_032/SideQuest/SideQuestApplication.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/auth/config/SecurityConfiguration.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/auth/config/WebConfig.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/auth/dto/LoginDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/auth/filter/JwtAuthenticationFilter.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/auth/filter/JwtVerificationFilter.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/auth/handler/MemberAuthenticationSuccessHandler.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/auth/jwt/JwtTokenizer.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/auth/userdetails/MemberDetailsService.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/auth/utils/CustomAuthorityUtils.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/auth/utils/GetAuthUserUtils.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/domain/member/controller/MemberController.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/domain/member/dto/MemberPostDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/domain/member/entity/Member.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/domain/member/mapper/MemberMapper.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/domain/member/repository/MemberRepository.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/domain/member/service/MemberService.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/global/exception/BusinessLogicException.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/global/exception/ExceptionCode.java
  backend/SideQuest/src/main/resources/application.yml
  backend/SideQuest/src/test/java/com/main_032/SideQuest/SideQuestApplicationTests.java
  backend/sidequest/src/main/resources/application.yml
Labels: feat, [BE]

#30 Feature/home project
  frontend/__mocks__/api.ts
  frontend/__mocks__/dummy/project.ts
  frontend/components/Card.tsx
  frontend/components/Header.tsx
  frontend/components/MainPost.tsx
  frontend/components/PostBtn.tsx
  frontend/components/editor/Editor.tsx
  frontend/components/project/ProjectCard.tsx
  frontend/components/project/ProjectCarousel.tsx
  frontend/components/skeleton/ProjectSkeleton.tsx
  frontend/components/stack/Bubble.tsx
  frontend/components/stack/Stack.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/project/[id]/index.tsx
  frontend/pages/project/create.tsx
  frontend/pages/project/index.tsx
  frontend/styles/App.css
Labels: feat, [FE]

#33 style : position 변경
  frontend/components/Footer.tsx
Labels: [FE]

#34 fix : ProjectSkeleton UI 조건
  frontend/pages/project/index.tsx
Labels: [FE]

#58 fix : profileImgUrl -> profileImageUrl 변경
  backend/SideQuest/src/main/java/com/main_032/SideQuest/domain/member/entity/Member.java
  backend/SideQuest/src/main/resources/application.yml
Labels: [BE], Fix

#59 Be/feat/member entity
  backend/SideQuest/src/main/java/com/main_032/SideQuest/domain/member/entity/Member.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/domain/member/entity/MemberEvaluation.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/domain/member/entity/MemberTechStack.java
Labels: feat, [BE]

#64 feat : Project 관련 엔티티 작성
  backend/SideQuest/src/main/java/com/main_032/SideQuest/domain/member/entity/Member.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/domain/project/entity/ProAcceptedCrew.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/domain/project/entity/ProApplyCrew.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/domain/project/entity/ProField.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/domain/project/entity/ProPositionCrew.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/domain/project/entity/ProTechStack.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/domain/project/entity/Project.java
Labels: feat, [BE]

#65 feat.승현 엔티티 추가
  backend/SideQuest/src/main/java/com/main_032/SideQuest/domain/member/entity/MemberEvaluation.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/domain/message/entity/Message.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/domain/project/entity/Project.java
Labels: feat, [BE]

#66 feat.승현 엔티티 추가 pro
  backend/SideQuest/src/main/java/com/main_032/SideQuest/domain/project/entity/ProAnswer.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/domain/project/entity/ProAnswerLike.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/domain/project/entity/ProComment.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/domain/project/entity/ProCommentLike.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/domain/project/entity/ProjectWishList.java
Labels: feat, [BE]

#62 Feature/edit project
  frontend/__mocks__/dummy/project.ts
  frontend/components/Btn.tsx
  frontend/components/MainPost.tsx
  frontend/components/editor/Editor.tsx
  frontend/components/project/ProjectForm.tsx
  frontend/components/stack/SelectStack.tsx
  frontend/constant/constant.tsx
  frontend/hooks/react-query/useProject.tsx
  frontend/pages/project/[id]/edit.tsx
  frontend/pages/project/[id]/index.tsx
  frontend/pages/project/create.tsx
  frontend/pages/project/index.tsx
  frontend/styles/App.css
  frontend/types/types.ts
Labels: feat, [FE]

#67 design : footer style 수정
  frontend/components/Footer.tsx
  frontend/components/Header.tsx
  frontend/pages/index.tsx
Labels: feat, [FE]

#74 feat : enum 추가, BaseEntity 추가. 각 엔티티 PK 이름 id로 고침.
  backend/SideQuest/src/main/java/com/main_032/SideQuest/article/entity/Article.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/article/entity/ArticleAnswer.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/article/entity/ArticleAnswerLike.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/article/entity/ArticleCategory.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/article/entity/ArticleComment.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/article/entity/ArticleCommentLike.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/article/entity/ArticleTechStack.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/member/entity/Member.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/member/entity/MemberEvaluation.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/member/entity/MemberTechStack.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/message/entity/Chat.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/entity/ProAcceptedCrew.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/entity/ProAnswer.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/entity/ProAnswerLike.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/entity/ProApplyCrew.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/entity/ProComment.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/entity/ProCommentLike.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/entity/ProField.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/entity/ProPositionCrew.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/entity/ProTechStack.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/entity/Project.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/entity/ProjectPosition.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/entity/ProjectStatus.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/entity/ProjectWishList.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/util/entity/BaseEntity.java
Labels: feat, [BE]

#79 feat : Swagger 기능 추가
  backend/SideQuest/build.gradle
  backend/SideQuest/src/main/java/com/main_032/SideQuest/auth/filter/JwtVerificationFilter.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/member/controller/MemberController.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/member/dto/GetLoginMemberResponseDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/member/dto/MemberPostDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/member/entity/Member.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/member/entity/MemberEvaluation.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/member/entity/MemberTechStack.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/member/mapper/MemberMapper.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/member/repository/MemberTechStackRepository.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/member/service/MemberService.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/util/config/SwaggerConfig.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/util/dto/MultiResponseDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/util/dto/PageInfo.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/util/dto/SingleResponseDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/util/error/ExceptionMsg.java
  backend/SideQuest/src/main/resources/application.yml
Labels: feat, [BE]

#81 Refactor/community
  frontend/__mocks__/api.ts
  frontend/__mocks__/datas/community.json
  frontend/__mocks__/dummy/community.ts
  frontend/components/Footer.tsx
  frontend/components/Loading.tsx
  frontend/components/MainPost.tsx
  frontend/components/Pagenation.tsx
  frontend/components/button/Btn.tsx
  frontend/components/button/SubBtn.tsx
  frontend/components/community/CommunityForm.tsx
  frontend/components/community/Content.tsx
  frontend/components/community/ContentBottom.tsx
  frontend/components/community/ContentBottomFilter.tsx
  frontend/components/community/ContentItem.tsx
  frontend/components/community/ContentItemList.tsx
  frontend/components/community/ContentPageNation.tsx
  frontend/components/community/ContentTop.tsx
  frontend/components/community/PostAddPage.tsx
  frontend/components/community/PostAddPageContent.tsx
  frontend/components/community/SideBar.tsx
  frontend/components/community/SubPost.tsx
  frontend/components/community/ViewCommunity.tsx
  frontend/components/project/ProjectForm.tsx
  frontend/components/project/StacksBox.tsx
  frontend/components/stack/SelectStack.tsx
  frontend/constant/constant.tsx
  frontend/hooks/react-query/useCommunity.tsx
  frontend/hooks/react-query/usePost.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/community/[category].tsx
  frontend/pages/community/create.tsx
  frontend/pages/community/post/[id].tsx
  frontend/pages/project/[id]/index.tsx
  frontend/recoil/atom.ts
  frontend/types/community.ts
  frontend/types/types.ts
Labels: [FE]

#83 Feature/design
  frontend/components/Footer.tsx
  frontend/components/Header.tsx
  frontend/components/Slider.tsx
  frontend/public/images/bannerComputer.svg
  frontend/public/images/bannerDic.svg
  frontend/public/images/bannerMsg.svg
  frontend/public/images/circleLeft.svg
  frontend/public/images/circleRight.svg
  frontend/public/images/squareBg.svg
  frontend/styles/App.css
Labels: feat, [FE]

#84 Refactor/home
  frontend/components/ContentCardbox.tsx
  frontend/components/Header.tsx
  frontend/components/Slider.tsx
  frontend/components/community/Content.tsx
  frontend/components/community/SideBar.tsx
  frontend/components/community/ViewCommunity.tsx
  frontend/components/project/ProjectCardbox.tsx
  frontend/hooks/react-query/useCommunity.tsx
  frontend/pages/community/[category].tsx
  frontend/pages/community/create.tsx
  frontend/pages/community/post/[id].tsx
  frontend/pages/index.tsx
  frontend/pages/project/[id]/edit.tsx
  frontend/pages/project/[id]/index.tsx
  frontend/pages/project/create.tsx
  frontend/pages/project/index.tsx
  frontend/recoil/atom.ts
Labels: [FE], Fix, refactor

#88 feat. Project 기능 개발
  backend/SideQuest/src/main/java/com/main_032/SideQuest/member/dto/MemberPostDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/controller/ProjectController.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/dto/ProFieldPostDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/dto/ProPositionCrewPostDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/dto/ProTechStackPostDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/dto/ProjectPostDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/entity/ProField.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/entity/ProPositionCrew.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/entity/ProTechStack.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/entity/Project.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/mapper/ProFieldMapper.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/mapper/ProPositionCrewMapper.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/mapper/ProTechStackMapper.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/mapper/ProjectMapper.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/repository/ProFieldRepository.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/repository/ProPositionCrewRepository.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/repository/ProTechStackRepository.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/repository/ProjectRepository.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/service/ProFieldService.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/service/ProPositionCrewService.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/service/ProTechStackService.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/service/ProjectService.java
Labels: feat, [BE]

#89 feat : 게시글 작성,수정,상세조회,삭제 api 구현 완료
  backend/SideQuest/src/main/java/com/main_032/SideQuest/article/controller/ArticleController.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/article/dto/ArticleGetResponseDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/article/dto/ArticlePatchDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/article/dto/ArticlePostDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/article/dto/ArticleResponseDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/article/dto/ArticleTechStackPostDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/article/dto/ArticleTechStackResponseDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/article/dto/ArticledeleteDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/article/entity/Article.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/article/entity/ArticleTechStack.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/article/mapper/ArticleMapper.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/article/repository/ArticleRepository.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/article/repository/ArticleTechStackRepository.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/article/service/ArticleService.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/article/service/ArticleTechStackService.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/entity/Answer.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/member/controller/MemberController.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/member/dto/GetMemberResponseDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/member/dto/LoginPostDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/member/dto/LoginResponseDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/member/dto/MemberPatchDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/member/dto/MemberTechStackResponseDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/member/entity/Member.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/member/entity/MemberTechStack.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/member/mapper/MemberMapper.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/member/repository/MemberRepository.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/member/repository/MemberTechStackRepository.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/member/service/MemberService.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/member/service/MemberTechStackService.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/util/exception/ExceptionCode.java
  backend/SideQuest/src/main/resources/application.yml
Labels: feat, [BE]

#90 feat : 멤버 쪽 기능구현
  backend/SideQuest/src/main/resources/application.yml
Labels: feat, [BE]

#91 Feature/home - 모달 추가
  frontend/components/Contact.tsx
  frontend/components/Modal.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/index.tsx
Labels: feat, [FE]

#87 Refactor/variable
  frontend/components/ContentCardbox.tsx
  frontend/components/Header.tsx
  frontend/components/authAction/LoginForm.tsx
  frontend/components/card_box/CommunityCardBox.tsx
  frontend/components/card_box/ProjectCardBox.tsx
  frontend/components/community/Content.tsx
  frontend/components/community/SideBar.tsx
  frontend/components/community/ViewCommunity.tsx
  frontend/components/project/ProjectCard.tsx
  frontend/components/project/ProjectForm.tsx
  frontend/components/skeleton/CommunityItemSkeleton.tsx
  frontend/components/stack/SelectStack.tsx
  frontend/components/user/UserCard.tsx
  frontend/constant/constant.tsx
  frontend/hooks/react-query/useAuth.ts
  frontend/hooks/react-query/useUser.ts
  frontend/pages/404.tsx
  frontend/pages/index.tsx
  frontend/pages/project/index.tsx
  frontend/pages/users/[id]/index.tsx
  frontend/pages/users/index.tsx
  frontend/pages/users/login/index.tsx
  frontend/pages/users/me/edit.tsx
  frontend/pages/users/me/index.tsx
  frontend/pages/users/signup/index.tsx
  frontend/recoil/atom.ts
  frontend/types/types.ts
Labels: [FE], refactor

#106 feat : 게시판 검색,목록 조회, 삭제, 기능,게시판 목록 조회,게시판 검색 조회 구현 완료
  backend/SideQuest/src/main/java/com/main_032/SideQuest/article/controller/ArticleController.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/article/dto/ArticleGetResponseDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/article/dto/ArticleResponseDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/article/entity/Article.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/article/mapper/ArticleMapper.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/article/repository/ArticleRepository.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/article/service/ArticleService.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/article/service/ArticleTechStackService.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/entity/Answer.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/entity/Comment.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/entity/Likes.java
  backend/SideQuest/src/main/resources/application.yml
Labels: feat, [BE]

#111 Feature/project api
  frontend/__mocks__/api.ts
  frontend/__mocks__/browser.ts
  frontend/__mocks__/datas/users.json
  frontend/__mocks__/dummy/users.ts
  frontend/__mocks__/server.ts
  frontend/components/Footer.tsx
  frontend/components/Header.tsx
  frontend/components/Modal.tsx
  frontend/components/authAction/LoginForm.tsx
  frontend/components/authAction/usePostApi.ts
  frontend/components/user/UserCard.tsx
  frontend/components/user/UserProfile.tsx
  frontend/constant/constant.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/_app.tsx
  frontend/pages/index.tsx
  frontend/pages/project/index.tsx
  frontend/pages/users/[id]/index.tsx
  frontend/pages/users/index.tsx
  frontend/pages/users/me/edit.tsx
  frontend/recoil/atom.ts
  frontend/styles/App.css
  frontend/types/user.ts
  frontend/util/api/index.ts
  frontend/util/api/user.ts
  frontend/util/cookie.ts
  frontend/util/cookie/index.ts
  frontend/util/local_storage/localStorage.ts
Labels: feat, [FE]

#115 Feature/project api
  frontend/components/card_box/ProjectCardBox.tsx
  frontend/components/project/ProjectCard.tsx
  frontend/components/project/ProjectForm.tsx
  frontend/components/project/StacksBox.tsx
  frontend/components/project/TagBox.tsx
  frontend/components/stack/Bubble.tsx
  frontend/components/stack/SelectStack.tsx
  frontend/components/stack/Stack.tsx
  frontend/hooks/react-query/useCommunity.tsx
  frontend/hooks/react-query/useProject.tsx
  frontend/pages/index.tsx
  frontend/pages/project/[id]/index.tsx
  frontend/pages/project/index.tsx
  frontend/types/community.ts
  frontend/types/project.ts
  frontend/types/types.ts
Labels: feat, [FE]

#116 feat : 답글 작성,수정, 삭제, 프로젝트,게시글 답글 조회 기능 구현
  backend/SideQuest/src/main/java/com/main_032/SideQuest/article/controller/ArticleController.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/article/service/ArticleService.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/Mapper/AnswerMapper.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/Mapper/CategoryMapper.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/Mapper/ChatMapper.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/Mapper/CommentMapper.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/Mapper/LikesMapper.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/controller/CommunityController.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/dto/AnswerPatchDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/dto/AnswerPostDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/dto/AnswerResponseDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/dto/CategoryDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/dto/ChatDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/dto/CommentDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/dto/LikesDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/entity/Answer.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/entity/Comment.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/entity/Likes.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/repository/AnswerRepository.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/repository/CategoryRepository.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/repository/ChatRepository.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/repository/CommentRepository.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/repository/LikesRepository.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/service/AnswerService.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/service/CategoryService.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/service/ChatService.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/service/CommentService.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/service/LikesService.java
Labels: feat, [BE]

#117 Dev/fe
  frontend/.gitignore
  frontend/__mocks__/api.ts
  frontend/__mocks__/browser.ts
  frontend/__mocks__/datas/users.json
  frontend/__mocks__/dummy/users.ts
  frontend/__mocks__/server.ts
  frontend/components/BannerSlider.tsx
  frontend/components/Card.tsx
  frontend/components/Header.tsx
  frontend/components/Tag.tsx
  frontend/components/authAction/LoginForm.tsx
  frontend/components/authAction/SignUpForm.tsx
  frontend/components/authAction/usePostApi.ts
  frontend/components/button/Btn.tsx
  frontend/components/card_box/ProjectCardBox.tsx
  frontend/components/project/PeriodBox.tsx
  frontend/components/project/ProjectCard.tsx
  frontend/components/project/ProjectForm.tsx
  frontend/components/project/StacksBox.tsx
  frontend/components/project/TagBox.tsx
  frontend/components/stack/Bubble.tsx
  frontend/components/stack/SelectStack.tsx
  frontend/components/stack/Stack.tsx
  frontend/components/user/UserCard.tsx
  frontend/components/user/UserProfile.tsx
  frontend/components/user/UserSideBar.tsx
  frontend/constant/constant.tsx
  frontend/hooks/react-query/useCommunity.tsx
  frontend/hooks/react-query/useProject.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/index.tsx
  frontend/pages/project/[id]/index.tsx
  frontend/pages/project/index.tsx
  frontend/pages/users/index.tsx
  frontend/pages/users/me/edit.tsx
  frontend/pages/users/signup/index.tsx
  frontend/public/images/thum (1).svg
  frontend/public/images/thum (2).svg
  frontend/public/images/thum (3).svg
  frontend/public/images/thum (4).svg
  frontend/public/images/thum (5).svg
  frontend/recoil/atom.ts
  frontend/styles/App.css
  frontend/types/community.ts
  frontend/types/project.ts
  frontend/types/types.ts
  frontend/types/user.ts
  frontend/util/api/index.ts
  frontend/util/api/user.ts
  frontend/util/cookie/index.ts
  frontend/util/local_storage/localStorage.ts
  package-lock.json
Labels: [FE]

#118 Test/deploy
  frontend/components/community/Content.tsx
  frontend/components/project/ProjectForm.tsx
  frontend/pages/index.tsx
  frontend/util/api/index.ts
  frontend/util/date/index.ts
Labels: [FE]

#121 feat : community 기능 추가 완료
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/Mapper/AnswerMapper.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/Mapper/CategoryMapper.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/Mapper/ChatMapper.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/Mapper/CommentMapper.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/Mapper/LikesMapper.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/controller/CommunityController.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/dto/AnswerDto/AnswerPatchDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/dto/AnswerDto/AnswerPostDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/dto/AnswerDto/AnswerResponseDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/dto/CategoryDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/dto/ChatDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/dto/CommentDto/CommenntAriticle/CommentArticleDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/dto/CommentDto/CommenntAriticle/CommentArticleRequest.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/dto/CommentDto/CommenntAriticle/CommentArticleResponse.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/dto/CommentDto/CommentProject/CommentProjectDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/dto/CommentDto/CommentProject/CommentProjectRequest.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/dto/CommentDto/CommentProject/CommentProjectResponse.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/dto/LikesPostDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/entity/Answer.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/entity/Category.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/entity/Comment.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/entity/Likes.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/repository/AnswerRepository.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/repository/CategoryRepository.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/repository/ChatRepository.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/repository/Commnet/CommentRepository.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/repository/LikesRepository.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/service/AnswerService.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/service/CategoryService.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/service/ChatService.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/service/CommentService.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/service/LikesService.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/util/exception/ExceptionCode.java
Labels: feat, [BE]

#123 Feature/project api
  frontend/components/Header.tsx
  frontend/components/authAction/SignUpForm.tsx
  frontend/components/authAction/usePostApi.ts
  frontend/components/community/CommunityForm.tsx
  frontend/components/community/Content.tsx
  frontend/components/project/ProjectCard.tsx
  frontend/components/project/ProjectCarousel.tsx
  frontend/components/project/ProjectForm.tsx
  frontend/dummy/community.ts
  frontend/dummy/project.ts
  frontend/dummy/users.ts
  frontend/pages/community/index.tsx
  frontend/pages/index.tsx
  frontend/pages/project/[id]/index.tsx
  frontend/pages/users/[id]/index.tsx
  frontend/recoil/atom.ts
  frontend/types/community.ts
  frontend/types/user.ts
  frontend/util/api/index.ts
  frontend/util/api/user.ts
  frontend/util/date/index.ts
  package-lock.json
Labels: feat, [FE]

#125 feat : 프로젝트 기능 구현
  backend/SideQuest/src/main/java/com/main_032/SideQuest/auth/config/SecurityConfiguration.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/member/controller/MemberController.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/member/dto/MemberGetResponseDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/member/mapper/MemberMapper.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/member/service/MemberService.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/controller/ProjectController.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/dto/ProApplyCrewResponseDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/dto/ProCancelAcceptedApplyDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/dto/ProFieldPostDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/dto/ProUpdateStatusDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/dto/ProjectApplyPostDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/dto/ProjectCancelApplyPostDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/dto/ProjectGetResponseDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/dto/ProjectLikesTop5Dto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/dto/ProjectViewsTop5Dto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/entity/ProAcceptedCrew.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/entity/ProApplyCrew.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/entity/ProPositionCrew.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/entity/Project.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/mapper/ProFieldMapper.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/mapper/ProjectMapper.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/repository/ProAcceptedCrewRepository.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/repository/ProApplyCrewRepository.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/repository/ProjectRepository.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/service/ProAcceptedCrewService.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/service/ProApplyCrewService.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/service/ProFieldService.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/service/ProPositionCrewService.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/service/ProjectService.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/util/exception/ExceptionCode.java
Labels: feat, [BE]

#126 Feature/project api
  frontend/components/CommentBox.tsx
  frontend/components/Header.tsx
  frontend/components/MainPost.tsx
  frontend/components/authAction/LoginForm.tsx
  frontend/components/authAction/SignUpForm.tsx
  frontend/components/authAction/usePostApi.ts
  frontend/components/community/CommunityForm.tsx
  frontend/components/community/Content.tsx
  frontend/components/community/ContentItem.tsx
  frontend/components/community/ViewCommunity.tsx
  frontend/components/editor/Editor.tsx
  frontend/components/project/ProjectCard.tsx
  frontend/components/project/ProjectForm.tsx
  frontend/constant/constant.tsx
  frontend/hooks/react-query/useProject.tsx
  frontend/hooks/useLogin.ts
  frontend/pages/community/index.tsx
  frontend/pages/index.tsx
  frontend/pages/project/[id]/index.tsx
  frontend/tsconfig.json
  frontend/types/community.ts
  frontend/types/user.ts
  frontend/util/api/index.ts
Labels: feat, [FE]

#128 feat : member info catch 처리
  frontend/components/CommentBox.tsx
  frontend/components/Header.tsx
  frontend/components/project/ProjectCard.tsx
Labels: feat, [FE]

#130 refactor : api 주소 변경, dto 이름 변경
  backend/SideQuest/src/main/java/com/main_032/SideQuest/article/controller/ArticleController.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/article/dto/ArticleGetResponseDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/article/dto/ArticleLikesTop5Dto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/article/dto/ArticlePatchDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/article/dto/ArticlePostDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/article/dto/ArticleResponseDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/article/dto/ArticleViewsTop5Dto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/article/entity/ArticleCategory.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/article/mapper/ArticleMapper.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/article/service/ArticleService.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/auth/config/SecurityConfiguration.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/auth/config/WebConfig.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/auth/filter/JwtAuthenticationFilter.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/Mapper/AnswerMapper.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/Mapper/LikesMapper.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/controller/CommunityController.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/dto/AnswerDto/AnswerPostDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/dto/AnswerDto/AnswerResponseDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/dto/CategoryDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/dto/ChatDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/dto/CommentDto/CommentResponseDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/dto/LikesPostDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/entity/Answer.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/entity/Category.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/service/AnswerService.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/service/CommentService.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/service/LikesService.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/member/controller/MemberController.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/controller/ProjectController.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/dto/ProApplyCrewResponseDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/dto/ProPositionCrewPostDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/dto/ProTechStackPostDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/dto/ProjectGetResponseDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/dto/ProjectLikesTop5Dto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/dto/ProjectPatchDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/dto/ProjectPostDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/dto/ProjectViewsTop5Dto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/mapper/ProPositionCrewMapper.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/mapper/ProTechStackMapper.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/service/ProPositionCrewService.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/service/ProTechStackService.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/service/ProjectService.java
Labels: feat, [BE]

#131 feat : S3
  backend/SideQuest/build.gradle
  backend/SideQuest/src/main/java/com/main_032/SideQuest/image/controller/ImageController.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/image/service/ImageUploadService.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/image/service/ImageUploader.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/uploadfile/config/LocalUploaderConfig.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/uploadfile/config/ProdUploaderConfig.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/uploadfile/config/S3BucketConfig.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/uploadfile/service/LocalUploader.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/uploadfile/service/S3Uploader.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/uploadfile/service/Uploader.java
  backend/SideQuest/src/main/resources/application.yml
  backend/SideQuest/src/main/resources/static/images/tmp_image.png
  backend/SideQuest/tmp/tmp
  backend/tmp/tmp
Labels: feat, [BE]

#132 Feature/project api
  frontend/components/CommentBox.tsx
  frontend/components/Header.tsx
  frontend/components/MainPost.tsx
  frontend/components/authAction/LoginForm.tsx
  frontend/components/authAction/SignUpForm.tsx
  frontend/components/card_box/ProjectCardBox.tsx
  frontend/components/community/CommunityForm.tsx
  frontend/components/community/Content.tsx
  frontend/components/community/ContentItem.tsx
  frontend/components/community/ViewCommunity.tsx
  frontend/components/project/ProjectCard.tsx
  frontend/components/project/ProjectForm.tsx
  frontend/constant/constant.tsx
  frontend/hooks/react-query/useProject.tsx
  frontend/hooks/react-query/useTop5Data.tsx
  frontend/hooks/useLogin.ts
  frontend/pages/_app.tsx
  frontend/pages/index.tsx
  frontend/pages/project/[id]/index.tsx
  frontend/pages/project/index.tsx
  frontend/public/mockServiceWorker.js
  frontend/tsconfig.json
  frontend/types/answer.ts
  frontend/types/comment.ts
  frontend/types/community.ts
  frontend/types/project.ts
  frontend/types/types.ts
  frontend/types/user.ts
  frontend/util/api/ProjectFilter.ts
  frontend/util/api/index.ts
Labels: [FE], refactor

#133 Feature/project api
  frontend/components/AnswerBox.tsx
  frontend/components/CommentBox.tsx
  frontend/components/Header.tsx
  frontend/components/card_box/CommunityCardBox.tsx
  frontend/components/community/CommunityForm.tsx
  frontend/components/community/Content.tsx
  frontend/components/community/ContentItem.tsx
  frontend/components/community/ViewCommunity.tsx
  frontend/components/editor/Editor.tsx
  frontend/components/project/ProjectCard.tsx
  frontend/components/project/ProjectForm.tsx
  frontend/hooks/react-query/answer/useAnswer.tsx
  frontend/hooks/react-query/answer/useGetAnswer.tsx
  frontend/hooks/react-query/comment/useComment.tsx
  frontend/hooks/react-query/comment/useGetComment.tsx
  frontend/hooks/react-query/community/useCommunity.tsx
  frontend/hooks/react-query/project/useProject.tsx
  frontend/hooks/react-query/project/useProjectApply.tsx
  frontend/hooks/react-query/useProject.tsx
  frontend/hooks/react-query/useTopData.tsx
  frontend/pages/_app.tsx
  frontend/pages/index.tsx
  frontend/pages/project/[id]/index.tsx
  frontend/types/community.ts
  frontend/types/types.ts
Labels: feat, [FE]

#135 feat : 게시글 조회에서 사용자의 답변, 댓글여부 확인 기능 구현 완료
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/Mapper/AnswerMapper.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/dto/AnswerDto/AnswerResponseDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/dto/CommentDto/CommentResponseDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/service/CommentService.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/member/service/MemberService.java
Labels: feat, [BE]

#139 feat : 게시글, 프로젝트 댓글갯수 추가 기능 수정 및 테스트 완료
  backend/SideQuest/src/main/java/com/main_032/SideQuest/article/dto/ArticleGetResponseDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/article/entity/Article.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/article/mapper/ArticleMapper.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/service/AnswerService.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/dto/ProjectGetResponseDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/entity/Project.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/mapper/ProjectMapper.java
  backend/SideQuest/src/main/resources/application.yml
Labels: feat, [BE]

#140 feat : 좋아요 기능 추가, 작성 여부, 좋아요 여부 확인 데이터 추가
  backend/SideQuest/src/main/java/com/main_032/SideQuest/article/controller/ArticleController.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/article/dto/ArticleGetResponseDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/article/entity/Article.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/article/mapper/ArticleMapper.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/article/service/ArticleService.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/Mapper/CategoryMapper.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/Mapper/ChatMapper.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/Mapper/CommentMapper.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/Mapper/LikesMapper.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/controller/CommunityController.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/dto/AnswerDto/AnswerPatchDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/dto/answer/AnswerPatchDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/dto/answer/AnswerPostDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/dto/answer/AnswerResponseDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/dto/comment/CommentPatchDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/dto/comment/CommentPostDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/dto/comment/CommentResponseDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/dto/likes/LikesPostDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/dto/likes/LikesUndoPostDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/entity/Answer.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/entity/Comment.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/entity/Likes.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/mapper/AnswerMapper.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/mapper/CategoryMapper.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/mapper/ChatMapper.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/mapper/CommentMapper.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/mapper/LikesMapper.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/repository/LikesRepository.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/service/AnswerService.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/service/CommentService.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/service/LikesService.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/member/service/MemberService.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/controller/ProjectController.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/dto/ProjectGetResponseDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/entity/Project.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/mapper/ProjectMapper.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/service/ProAcceptedCrewService.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/service/ProApplyCrewService.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/service/ProPositionCrewService.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/service/ProjectService.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/util/exception/ExceptionCode.java
Labels: feat, [BE]

#141 Feature/project api
  frontend/components/AnswerBox.tsx
  frontend/components/Contact.tsx
  frontend/components/Footer.tsx
  frontend/components/Header.tsx
  frontend/components/MainPost.tsx
  frontend/components/answer/AnswerBox.tsx
  frontend/components/answer/AnswerItem.tsx
  frontend/components/comment/CommentBox.tsx
  frontend/components/community/CommunityForm.tsx
  frontend/components/community/ContentItem.tsx
  frontend/components/community/SideBar.tsx
  frontend/components/community/ViewCommunity.tsx
  frontend/components/project/PeriodBox.tsx
  frontend/components/project/ProjectCard.tsx
  frontend/components/project/ProjectForm.tsx
  frontend/components/project/TagBox.tsx
  frontend/components/stack/SelectStack.tsx
  frontend/constant/constant.tsx
  frontend/hooks/react-query/answer/useAnswer.tsx
  frontend/hooks/react-query/answer/useGetAnswer.tsx
  frontend/hooks/react-query/community/useCommunity.tsx
  frontend/hooks/react-query/project/useProject.tsx
  frontend/pages/_app.tsx
  frontend/pages/community/create.tsx
  frontend/pages/community/index.tsx
  frontend/pages/community/post/[id]/edit.tsx
  frontend/pages/project/[id]/index.tsx
  frontend/pages/project/index.tsx
  frontend/recoil/atom.ts
  frontend/types/answer.ts
  frontend/types/community.ts
  frontend/types/project.ts
  frontend/types/types.ts
  frontend/types/user.ts
  frontend/util/api/index.ts
Labels: feat, [FE]

#142 Feature/project api
  frontend/components/Filter.tsx
  frontend/components/Header.tsx
  frontend/components/MainPost.tsx
  frontend/components/ModalBg.tsx
  frontend/components/answer/AnswerBox.tsx
  frontend/components/answer/AnswerItem.tsx
  frontend/components/comment/CommentBox.tsx
  frontend/components/comment/CommentInput.tsx
  frontend/components/comment/CommentItem.tsx
  frontend/components/community/Content.tsx
  frontend/components/community/SideBar.tsx
  frontend/components/community/ViewCommunity.tsx
  frontend/components/project/PeriodBox.tsx
  frontend/components/project/StacksBox.tsx
  frontend/components/skeleton/AnswerSkeleton.tsx
  frontend/components/skeleton/ProjectSkeleton.tsx
  frontend/components/skeleton/Skeleton.tsx
  frontend/components/stack/SelectStack.tsx
  frontend/hooks/react-query/answer/useAnswer.tsx
  frontend/hooks/react-query/comment/useComment.tsx
  frontend/hooks/react-query/comment/useGetComment.tsx
  frontend/pages/_app.tsx
  frontend/pages/community/[category].tsx
  frontend/pages/index.tsx
  frontend/pages/project/[id]/index.tsx
  frontend/pages/project/create.tsx
  frontend/types/answer.ts
  frontend/types/comment.ts
  frontend/types/types.ts
  frontend/types/user.ts
  frontend/util/api/index.ts
Labels: feat, [FE]

#144 Feature/project api
  frontend/components/Header.tsx
  frontend/components/MainPost.tsx
  frontend/components/answer/AnswerBox.tsx
  frontend/components/answer/AnswerItem.tsx
  frontend/components/banner/BannerFirst.tsx
  frontend/components/banner/BannerSecond.tsx
  frontend/components/banner/BannerSlider.tsx
  frontend/components/banner/BannerThird.tsx
  frontend/components/banner/ParallaxBanner.tsx
  frontend/components/comment/CommentBox.tsx
  frontend/components/comment/CommentItem.tsx
  frontend/components/common_box/AuthorBox.tsx
  frontend/components/common_box/GridBox.tsx
  frontend/components/common_box/HeartBox.tsx
  frontend/components/common_box/MainArticleBox.tsx
  frontend/components/community/CommunityForm.tsx
  frontend/components/community/Content.tsx
  frontend/components/community/ViewCommunity.tsx
  frontend/components/project/ProjectForm.tsx
  frontend/components/project/TagBox.tsx
  frontend/components/stack/Bubble.tsx
  frontend/components/stack/Stack.tsx
  frontend/hooks/react-query/answer/useAnswer.tsx
  frontend/hooks/react-query/answer/useGetAnswer.tsx
  frontend/hooks/react-query/comment/useComment.tsx
  frontend/hooks/react-query/community/useCommunity.tsx
  frontend/hooks/react-query/project/useProject.tsx
  frontend/pages/_app.tsx
  frontend/pages/community/create.tsx
  frontend/pages/index.tsx
  frontend/pages/project/[id]/index.tsx
  frontend/pages/project/create.tsx
  frontend/types/answer.ts
  frontend/types/comment.ts
  frontend/types/community.ts
  frontend/types/project.ts
  frontend/util/api/index.ts
Labels: feat, [FE]

#147 Feature/api
  frontend/components/Filter.tsx
  frontend/components/community/Content.tsx
  frontend/components/community/SideBar.tsx
  frontend/constant/constant.tsx
  frontend/pages/community/[category].tsx
  frontend/pages/community/index.tsx
  frontend/pages/project/index.tsx
  frontend/types/project.ts
  frontend/types/types.ts
  frontend/util/api/getAllProject.ts
  frontend/util/filter/articleFilter.ts
  frontend/util/filter/communityFilter.ts
Labels: feat, [FE]

#148 Feature/api
  frontend/components/Header.tsx
  frontend/components/Tag.tsx
  frontend/components/answer/AnswerBox.tsx
  frontend/components/answer/AnswerItem.tsx
  frontend/components/authAction/AuthContainer.tsx
  frontend/components/authAction/LoginForm.tsx
  frontend/components/button/Btn.tsx
  frontend/components/button/ButtonStyle.tsx
  frontend/components/button/SubBtn.tsx
  frontend/components/card_box/ProjectCardBox.tsx
  frontend/components/comment/CommentItem.tsx
  frontend/components/common_box/ApplyBox.tsx
  frontend/components/common_box/MainArticleBox.tsx
  frontend/components/community/Content.tsx
  frontend/components/community/ViewCommunity.tsx
  frontend/components/project/ProjectCard.tsx
  frontend/components/project/StacksBox.tsx
  frontend/hooks/react-query/answer/useAnswer.tsx
  frontend/hooks/react-query/project/useProject.tsx
  frontend/hooks/react-query/project/useProjectApply.tsx
  frontend/hooks/react-query/useTopData.tsx
  frontend/hooks/useLogin.ts
  frontend/pages/community/create.tsx
  frontend/pages/community/post/[id]/edit.tsx
  frontend/pages/community/post/[id]/index.tsx
  frontend/pages/index.tsx
  frontend/pages/project/[id]/edit.tsx
  frontend/pages/project/[id]/index.tsx
  frontend/pages/project/create.tsx
  frontend/pages/project/index.tsx
  frontend/types/comment.ts
  frontend/types/project.ts
  frontend/types/user.ts
  frontend/util/api/index.ts
Labels: feat, [FE]

#158 Feature/api
  frontend/components/answer/AnswerItem.tsx
  frontend/components/authAction/AuthContainer.tsx
  frontend/components/authAction/LoginForm.tsx
  frontend/components/comment/CommentItem.tsx
  frontend/components/common_box/AuthorBox.tsx
  frontend/components/community/Content.tsx
  frontend/components/community/ViewCommunity.tsx
  frontend/components/project/PeriodBox.tsx
  frontend/components/project/ProjectCard.tsx
  frontend/components/user/InfoContainer.tsx
  frontend/components/user/UserContentsBox.tsx
  frontend/components/user/UserProfile.tsx
  frontend/components/user/UserSideBar.tsx
  frontend/constant/constant.tsx
  frontend/hooks/react-query/project/useProject.tsx
  frontend/hooks/react-query/project/useProjectApply.tsx
  frontend/hooks/react-query/useTopData.tsx
  frontend/pages/404.tsx
  frontend/pages/_app.tsx
  frontend/pages/community/create.tsx
  frontend/pages/community/post/[id]/edit.tsx
  frontend/pages/index.tsx
  frontend/pages/project/[id]/edit.tsx
  frontend/pages/project/[id]/index.tsx
  frontend/pages/project/create.tsx
  frontend/pages/project/index.tsx
  frontend/pages/users/index.tsx
  frontend/pages/users/login/index.tsx
  frontend/pages/users/me/edit.tsx
  frontend/pages/users/me/index.tsx
  frontend/pages/users/signup/confirm.tsx
  frontend/pages/users/signup/index.tsx
  frontend/util/api/index.ts
  frontend/util/filter/articleFilter.ts
Labels: feat, [FE], Fix

#165 Fix/flexible web
  frontend/components/answer/AnswerItem.tsx
  frontend/components/comment/CommentItem.tsx
  frontend/components/community/Content.tsx
  frontend/hooks/react-query/project/useInfinityProject.tsx
  frontend/hooks/react-query/project/useProject.tsx
  frontend/hooks/react-query/useAllData.tsx
  frontend/hooks/react-query/useTopData.tsx
  frontend/pages/project/index.tsx
  frontend/util/api/index.ts
Labels: feat, [FE]

#168 Fix/flexible web
  frontend/components/Footer.tsx
  frontend/components/Header.tsx
  frontend/components/Tag.tsx
  frontend/components/alert/Alert.tsx
  frontend/components/answer/AnswerItem.tsx
  frontend/components/button/ButtonStyle.tsx
  frontend/components/card_box/CommunityCardBox.tsx
  frontend/components/card_box/ProjectCardBox.tsx
  frontend/components/comment/CommentInput.tsx
  frontend/components/comment/CommentItem.tsx
  frontend/components/common_box/ApplyBox.tsx
  frontend/components/community/CommunityForm.tsx
  frontend/components/community/Content.tsx
  frontend/components/community/ViewCommunity.tsx
  frontend/components/project/ProjectCard.tsx
  frontend/components/project/ProjectForm.tsx
  frontend/constant/constant.tsx
  frontend/hooks/react-query/answer/useAnswer.tsx
  frontend/hooks/react-query/community/useCommunity.tsx
  frontend/hooks/react-query/project/useProject.tsx
  frontend/hooks/react-query/project/useProjectApply.tsx
  frontend/hooks/react-query/useAllData.tsx
  frontend/hooks/react-query/useTopData.tsx
  frontend/pages/community/create.tsx
  frontend/pages/community/post/[id]/edit.tsx
  frontend/pages/index.tsx
  frontend/pages/project/[id]/edit.tsx
  frontend/pages/project/[id]/index.tsx
  frontend/pages/project/create.tsx
  frontend/pages/project/index.tsx
  frontend/util/api/index.ts
  frontend/util/api/postStar.ts
  frontend/util/filter/articleFilter.ts
  frontend/util/filter/communityFilter.ts
  frontend/util/filter/projectFilter.ts
Labels: feat, [FE], Fix

#169 Feature/post star
  frontend/components/answer/AnswerBox.tsx
  frontend/components/answer/AnswerItem.tsx
  frontend/components/comment/CommentItem.tsx
  frontend/components/community/ViewCommunity.tsx
  frontend/components/project/ProjectCard.tsx
  frontend/components/skeleton/AnswerItemSkeleton.tsx
  frontend/hooks/react-query/answer/useAnswer.tsx
  frontend/hooks/react-query/comment/useComment.tsx
  frontend/hooks/react-query/community/useCommunity.tsx
  frontend/hooks/react-query/project/useProject.tsx
  frontend/hooks/react-query/project/useProjectApply.tsx
  frontend/pages/project/[id]/index.tsx
  frontend/recoil/selector.ts
  frontend/util/api/postStar.ts
Labels: feat, [FE]

#174 feat : 예외 처리
  backend/SideQuest/src/main/java/com/main_032/SideQuest/util/advice/GlobalExceptionAdvice.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/util/dto/SingleResponseDto.java
Labels: feat, [BE]

#175 test/deploy
  frontend/components/EtcHeader.tsx
  frontend/components/Header.tsx
  frontend/components/banner/BannerFirst.tsx
  frontend/components/banner/BannerSecond.tsx
  frontend/components/banner/BannerSlider.tsx
  frontend/components/banner/BannerText.tsx
  frontend/components/banner/BannerThird.tsx
  frontend/components/banner/CommuBanner.tsx
  frontend/components/banner/HomeBanner.tsx
  frontend/components/banner/ParallaxBanner.tsx
  frontend/components/card_box/CommunityCardBox.tsx
  frontend/components/community/Content.tsx
  frontend/components/community/ContentItem.tsx
  frontend/components/project/ProjectCard.tsx
  frontend/components/user/UserCard.tsx
  frontend/components/user/UserProfile.tsx
  frontend/constant/constant.tsx
  frontend/pages/_app.tsx
  frontend/pages/community/index.tsx
  frontend/pages/users/index.tsx
  frontend/pages/users/login/index.tsx
  frontend/pages/users/me/edit.tsx
  frontend/pages/users/me/index.tsx
  frontend/util/api/index.ts
Labels: [FE], deploy

#183 test/deploy
  frontend/pages/community/index.tsx
  frontend/pages/users/[id]/index.tsx
  frontend/types/user.ts
Labels: deploy

#186 feat : OAuth2 Google 구현
  backend/SideQuest/build.gradle
  backend/SideQuest/src/main/java/com/main_032/SideQuest/auth/config/SecurityConfiguration.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/auth/handler/MemberAuthenticationSuccessHandler.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/auth/handler/OAuth2SuccessHandler.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/member/service/MemberService.java
  backend/SideQuest/src/main/resources/application.yml
Labels: feat, [BE]

#187 feat : 마이페이지에서 프로젝트, 게시글,답글,댓글 조회 api 추가
  backend/SideQuest/src/main/java/com/main_032/SideQuest/article/dto/ArticleInfoResponseDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/article/mapper/ArticleMapper.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/article/repository/ArticleRepository.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/article/service/ArticleService.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/dto/answer/AnswerInfoResponseDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/dto/comment/CommentInfoResponseDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/mapper/AnswerMapper.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/repository/AnswerRepository.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/repository/CommentRepository.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/service/AnswerService.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/community/service/CommentService.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/member/controller/MemberController.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/dto/ProjectInfoResponseDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/mapper/ProjectMapper.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/repository/ProjectRepository.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/service/ProjectService.java
  backend/SideQuest/src/main/resources/application.yml
Labels: feat, [BE]

#191 Refactor/users
  frontend/components/authAction/LoginForm.tsx
  frontend/components/authAction/SignUpForm.tsx
  frontend/components/authAction/UserEditForm.tsx
  frontend/components/background/ModalBg.tsx
  frontend/components/background/StarBg.tsx
  frontend/components/common_box/AuthorBox.tsx
  frontend/components/community/ViewCommunity.tsx
  frontend/components/header/EtcHeader.tsx
  frontend/components/header/Header.tsx
  frontend/components/user/InfoContainer.tsx
  frontend/components/user/UserCard.tsx
  frontend/components/user/UserContentBox.tsx
  frontend/components/user/UserMeContentsBox.tsx
  frontend/components/user/UserProfile.tsx
  frontend/components/user/UserSideBar.tsx
  frontend/constant/constant.tsx
  frontend/hooks/react-query/user/useAuth.ts
  frontend/hooks/react-query/user/useLogin.ts
  frontend/hooks/react-query/user/useUser.ts
  frontend/pages/_app.tsx
  frontend/pages/about.tsx
  frontend/pages/project/[id]/index.tsx
  frontend/pages/users/[id]/index.tsx
  frontend/pages/users/index.tsx
  frontend/pages/users/login/index.tsx
  frontend/pages/users/me/edit.tsx
  frontend/pages/users/me/index.tsx
  frontend/pages/users/signup/confirm.tsx
  frontend/pages/users/signup/index.tsx
  frontend/util/filter/usersFilter.ts
Labels: feat, [FE], Fix, refactor

#193 fix : 배포 중, 발생한 오류
  frontend/components/project/PeriodBox.tsx
  frontend/components/project/ProjectForm.tsx
Labels: [FE], Fix

#194 test/deploy
  frontend/components/project/PeriodBox.tsx
  frontend/components/project/ProjectForm.tsx
Labels: deploy

#195 fix : 배포 중, 발생한 타입 오류
  frontend/components/project/PeriodBox.tsx
Labels: [FE], Fix

#196 test/deploy
  frontend/components/project/PeriodBox.tsx
Labels: deploy

#198 feat : 멤버정보에 totalProject 추가
  backend/SideQuest/src/main/java/com/main_032/SideQuest/member/dto/MemberGetResponseDto.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/member/mapper/MemberMapper.java
  backend/SideQuest/src/main/java/com/main_032/SideQuest/project/repository/ProAcceptedCrewRepository.java
Labels: feat, [BE]

#199 test/deploy
  frontend/components/authAction/AuthContainer.tsx
Labels: deploy

#204 test/deploy
  frontend/components/community/ViewCommunity.tsx
Labels: [FE], deploy

#205 test/deploy
  frontend/pages/chat/[id].tsx
  frontend/pages/chat/index.tsx
  frontend/recoil/atom.ts
Labels: [FE], Fix, deploy

#206 fix : 랜덤 이미지 오류 수정
  frontend/components/card_box/ProjectCardBox.tsx
  frontend/pages/index.tsx
  frontend/public/images/thum (1).svg
  frontend/public/images/thum (2).svg
  frontend/public/images/thum (3).svg
  frontend/public/images/thum (4).svg
  frontend/public/images/thum (5).svg
Labels: [FE], Fix

#207 fix : 자기소개 미 표시
  frontend/pages/users/[id]/index.tsx
Labels: [FE], Fix

#209 fix : retry, 요청 주소 변경
  frontend/pages/_app.tsx
  frontend/pages/index.tsx
  frontend/util/api/index.ts
Labels: [FE], deploy

#210 test/deploy
  frontend/components/authAction/AuthContainer.tsx
  frontend/components/authAction/EditInput.tsx
  frontend/components/authAction/UserEditForm.tsx
  frontend/components/user/InfoContainer.tsx
  frontend/hooks/react-query/user/useUser.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/oauth2.tsx
  frontend/pages/users/me/index.tsx
Labels: [FE], deploy

#211 test/deploy
  frontend/pages/chat/create.tsx
Labels: [FE], deploy

#212 Refactor/error redirection
  frontend/components/Contact.tsx
  frontend/components/answer/AnswerItem.tsx
  frontend/components/community/CommunityForm.tsx
  frontend/components/community/Content.tsx
  frontend/components/community/ViewCommunity.tsx
  frontend/components/header/EtcHeader.tsx
  frontend/components/user/UserContentBox.tsx
  frontend/components/user/UserMeContentsBox.tsx
  frontend/constant/constant.tsx
  frontend/hooks/react-query/user/useMemberInfo.tsx
  frontend/pages/chat/index.tsx
  frontend/pages/community/create.tsx
  frontend/pages/community/post/[id]/edit.tsx
  frontend/pages/community/post/[id]/index.tsx
  frontend/pages/index.tsx
  frontend/pages/project/[id]/index.tsx
  frontend/pages/project/index.tsx
  frontend/pages/users/[id]/index.tsx
  frontend/pages/users/index.tsx
  frontend/pages/users/me/edit.tsx
  frontend/pages/users/me/index.tsx
  frontend/pages/users/signup/confirm.tsx
Labels: [FE], Fix, refactor

#214 fix : 배포 중, 발생한 오류 수정
  frontend/components/user/UserContentBox.tsx
  frontend/components/user/UserMeContentsBox.tsx
Labels: [FE], Fix

#215 test/deploy
  frontend/components/user/UserContentBox.tsx
  frontend/components/user/UserMeContentsBox.tsx
Labels: [FE], deploy

#216 Dev/fe
  frontend/components/Contact.tsx
  frontend/components/community/CommunityForm.tsx
  frontend/components/community/Content.tsx
  frontend/components/project/ProjectForm.tsx
  frontend/components/user/UserContentBox.tsx
  frontend/components/user/UserMeContentsBox.tsx
  frontend/constant/constant.tsx
  frontend/pages/404.tsx
  frontend/pages/_document.tsx
  frontend/pages/about.tsx
  frontend/pages/chat/[id].tsx
  frontend/pages/chat/create.tsx
  frontend/pages/chat/index.tsx
  frontend/pages/community/create.tsx
  frontend/pages/community/index.tsx
  frontend/pages/community/post/[id]/edit.tsx
  frontend/pages/community/post/[id]/index.tsx
  frontend/pages/index.tsx
  frontend/pages/project/[id]/edit.tsx
  frontend/pages/project/[id]/index.tsx
  frontend/pages/project/create.tsx
  frontend/pages/project/index.tsx
  frontend/pages/users/[id]/index.tsx
  frontend/pages/users/index.tsx
  frontend/pages/users/login/index.tsx
  frontend/pages/users/me/edit.tsx
  frontend/pages/users/me/index.tsx
  frontend/pages/users/signup/confirm.tsx
  frontend/pages/users/signup/index.tsx
  frontend/public/favicon.png
Labels: feat, [FE]

#217 test/deploy
  frontend/components/user/UserContentBox.tsx
  frontend/components/user/UserMeContentsBox.tsx
Labels: [FE], deploy

#220 fix : 요청 주소 https 적용
  frontend/util/api/index.ts
Labels: [FE], Fix, deploy

#222 Dev/fe
  frontend/components/MainPost.tsx
  frontend/components/authAction/UserEditForm.tsx
  frontend/components/community/CommunityForm.tsx
  frontend/components/project/ProjectForm.tsx
  frontend/components/stack/SelectStack.tsx
Labels: [FE], Fix, deploy

#223 fix : 포지션 미 설정 시
  frontend/pages/users/me/index.tsx
Labels: [FE], Fix, deploy

#224 fix : 포지션 표출 문제
  frontend/components/user/UserProfile.tsx
  frontend/pages/users/me/index.tsx
Labels: [FE], Fix, deploy

#225 Dev/fe
  frontend/components/Footer.tsx
  frontend/package-lock.json
  frontend/package.json
Labels: [FE], Fix, deploy

#226 fix : elapsedTime 함수
  frontend/util/date/index.ts
Labels: [FE], Fix, deploy

#227 style : common box에서 사용되는 컴포넌트들 padding 조정
  frontend/components/project/PeriodBox.tsx
  frontend/components/project/StacksBox.tsx
  frontend/components/project/TagBox.tsx
  frontend/pages/project/[id]/index.tsx
Labels: [FE], Fix, deploy

#228 Feat/user event
  frontend/components/MainPost.tsx
  frontend/components/common_box/ApplyBox.tsx
  frontend/components/common_box/AuthorBox.tsx
  frontend/components/common_box/GridBox.tsx
  frontend/components/project/ProjectForm.tsx
  frontend/pages/project/index.tsx
Labels: feat, [FE], Fix, deploy

#229 Dev/fe
  frontend/components/MainPost.tsx
  frontend/components/common_box/ApplyBox.tsx
  frontend/components/common_box/AuthorBox.tsx
  frontend/components/common_box/GridBox.tsx
  frontend/components/project/ProjectForm.tsx
  frontend/pages/project/index.tsx
Labels: [FE], deploy

#230 Refactor/flexible web
  frontend/components/authAction/AuthContainer.tsx
  frontend/components/authAction/LoginForm.tsx
  frontend/components/banner/Banner.tsx
  frontend/components/banner/BannerSlider.tsx
  frontend/components/banner/BannerText.tsx
  frontend/components/community/Content.tsx
  frontend/components/community/ContentItem.tsx
  frontend/components/header/Header.tsx
  frontend/components/user/LoginBg.tsx
  frontend/components/user/UserCard.tsx
  frontend/constant/constant.tsx
  frontend/pages/404.tsx
  frontend/pages/_document.tsx
  frontend/pages/about.tsx
  frontend/pages/chat/[id].tsx
  frontend/pages/chat/create.tsx
  frontend/pages/chat/index.tsx
  frontend/pages/community/create.tsx
  frontend/pages/community/index.tsx
  frontend/pages/community/post/[id]/edit.tsx
  frontend/pages/community/post/[id]/index.tsx
  frontend/pages/index.tsx
  frontend/pages/project/[id]/edit.tsx
  frontend/pages/project/[id]/index.tsx
  frontend/pages/project/create.tsx
  frontend/pages/project/index.tsx
  frontend/pages/users/[id]/index.tsx
  frontend/pages/users/index.tsx
  frontend/pages/users/login/index.tsx
  frontend/pages/users/me/edit.tsx
  frontend/pages/users/me/index.tsx
  frontend/pages/users/signup/confirm.tsx
  frontend/pages/users/signup/index.tsx
Labels: [FE], Fix, refactor

#231 Refactor/flexible web
  frontend/components/authAction/SignUpForm.tsx
  frontend/components/header/EtcHeader.tsx
  frontend/components/user/LoginBg.tsx
  frontend/pages/users/login/index.tsx
  frontend/pages/users/signup/index.tsx
Labels: [FE], Fix

#232 Refactor/flexible web
  frontend/components/authAction/AuthContainer.tsx
  frontend/components/authAction/LoginForm.tsx
  frontend/components/authAction/SignUpForm.tsx
  frontend/components/banner/Banner.tsx
  frontend/components/banner/BannerSlider.tsx
  frontend/components/banner/BannerText.tsx
  frontend/components/community/Content.tsx
  frontend/components/community/ContentItem.tsx
  frontend/components/header/EtcHeader.tsx
  frontend/components/header/Header.tsx
  frontend/components/user/LoginBg.tsx
  frontend/components/user/UserCard.tsx
  frontend/pages/404.tsx
  frontend/pages/about.tsx
  frontend/pages/chat/[id].tsx
  frontend/pages/chat/create.tsx
  frontend/pages/chat/index.tsx
  frontend/pages/community/create.tsx
  frontend/pages/community/index.tsx
  frontend/pages/community/post/[id]/edit.tsx
  frontend/pages/community/post/[id]/index.tsx
  frontend/pages/index.tsx
  frontend/pages/project/[id]/edit.tsx
  frontend/pages/project/[id]/index.tsx
  frontend/pages/project/create.tsx
  frontend/pages/project/index.tsx
  frontend/pages/users/[id]/index.tsx
  frontend/pages/users/index.tsx
  frontend/pages/users/login/index.tsx
  frontend/pages/users/me/edit.tsx
  frontend/pages/users/me/index.tsx
  frontend/pages/users/signup/confirm.tsx
  frontend/pages/users/signup/index.tsx
Labels: [FE], Fix, refactor

#233 Dev/fe
  frontend/components/user/LoginBg.tsx
Labels: [FE], Fix

#235 fix : 유저 필터 정상화
  frontend/components/common_box/ApplyBox.tsx
  frontend/hooks/react-query/useAllData.tsx
  frontend/pages/users/index.tsx
Labels: [FE], Fix

#236 Dev/fe
  frontend/components/common_box/ApplyBox.tsx
  frontend/hooks/react-query/useAllData.tsx
  frontend/pages/users/index.tsx
Labels: [FE], deploy

#238 Fix/skeleton UI
  frontend/components/community/Content.tsx
  frontend/components/skeleton/CommunityItemSkeleton.tsx
  frontend/components/skeleton/UserItemSkeleton.tsx
  frontend/pages/index.tsx
  frontend/pages/users/index.tsx
Labels: [FE], Fix

#239 Dev/fe
  frontend/components/community/Content.tsx
  frontend/components/skeleton/CommunityItemSkeleton.tsx
  frontend/components/skeleton/UserItemSkeleton.tsx
  frontend/components/user/UserCard.tsx
  frontend/pages/index.tsx
  frontend/pages/users/index.tsx
Labels: [FE], Fix

#240 fix : footer 정상화
  frontend/components/Footer.tsx
  frontend/constant/constant.tsx
Labels: [FE], Fix

#244 feat : 프로젝트 지원, 확정 취소 쪽지 이벤트
  frontend/pages/project/[id]/index.tsx
Labels: feat, [FE]

#245 fix : 쪽지 전달 설정 문제
  frontend/pages/project/[id]/index.tsx
Labels: [FE], Fix

#246 fix : style 변경으로 인한 카드 스켈레톤UI 수정
  frontend/components/skeleton/CommunityItemSkeleton.tsx
  frontend/components/skeleton/UserItemSkeleton.tsx
  frontend/components/user/UserCard.tsx
  frontend/pages/index.tsx
Labels: [FE], Fix

#247 fix : 배포 중 발생한 오류
  frontend/components/skeleton/CommunityItemSkeleton.tsx
Labels: [FE], deploy

#248 Dev/fe
  frontend/.babelrc
  frontend/components/user/LoginBg.tsx
  frontend/pages/project/index.tsx
  frontend/recoil/atom.ts
  frontend/util/filter/communityFilter.ts
  frontend/util/filter/projectFilter.ts
Labels: [FE], Fix

#249 feat : 명예, 별점 설명 추가
  frontend/components/InfoBubble.tsx
  frontend/components/card_box/UserCardBox.tsx
  frontend/pages/project/[id]/index.tsx
Labels: feat, [FE]

#250 Dev/fe
  frontend/components/header/Header.tsx
  frontend/pages/users/me/index.tsx
Labels: [FE], Fix

#251 refactor : 쪽지 스타일 및 시간 구조 변경
  frontend/pages/chat/[id].tsx
  frontend/pages/chat/create.tsx
  frontend/pages/chat/index.tsx
  frontend/pages/users/[id]/index.tsx
  frontend/pages/users/me/index.tsx
  frontend/util/date/index.ts
Labels: [FE], Fix

#252 Dev/fe
  frontend/components/community/Content.tsx
  frontend/components/community/ContentItem.tsx
  frontend/components/header/Header.tsx
  frontend/components/project/ProjectCard.tsx
  frontend/components/stack/Bubble.tsx
  frontend/components/stack/Stack.tsx
  frontend/components/user/UserCard.tsx
  frontend/pages/project/index.tsx
  frontend/pages/users/index.tsx
  frontend/pages/users/me/index.tsx
  frontend/recoil/atom.ts
  frontend/util/filter/communityFilter.ts
  frontend/util/filter/projectFilter.ts
Labels: feat, [FE], Fix

#253 fix : 무한 스크롤 조건 추가
  frontend/pages/project/index.tsx
Labels: [FE], Fix

#254 feat : sns 로그인 error 처리
  frontend/components/authAction/AuthContainer.tsx
Labels: feat, [FE]

#255 Dev/fe
  frontend/components/community/Content.tsx
  frontend/components/community/ContentItem.tsx
  frontend/components/header/Header.tsx
  frontend/components/project/ProjectCard.tsx
  frontend/pages/project/index.tsx
  frontend/pages/users/index.tsx
  frontend/recoil/atom.ts
Labels: [FE], refactor

#256 feat : 회원탈퇴 기능
  frontend/pages/users/me/index.tsx
Labels: feat, [FE]

#257 fix : 회원 탈퇴 시, 토큰 제거 추가
  frontend/pages/users/me/index.tsx
Labels: feat, [FE]

#259 Dev/fe
  frontend/components/Contact.tsx
  frontend/components/Filter.tsx
  frontend/components/MainPost.tsx
  frontend/components/banner/Banner.tsx
  frontend/components/banner/BannerSlider.tsx
  frontend/components/banner/BannerText.tsx
  frontend/components/card_box/UserCardBox.tsx
  frontend/components/common_box/AuthorBox.tsx
  frontend/components/common_box/HeartBox.tsx
  frontend/components/common_box/MainArticleBox.tsx
  frontend/components/community/Content.tsx
  frontend/components/editor/Editor.tsx
  frontend/components/header/Header.tsx
  frontend/components/project/ProjectCard.tsx
  frontend/components/project/ProjectForm.tsx
  frontend/components/user/UserCard.tsx
  frontend/components/user/UserMeContentsBox.tsx
  frontend/pages/_app.tsx
  frontend/pages/about.tsx
  frontend/pages/project/index.tsx
  frontend/pages/users/index.tsx
  frontend/public/images/symbol.svg
  frontend/public/images/symbolOriginal.svg
  frontend/public/images/symbolWhite.svg
  frontend/util/api/uploadImg.ts
Labels: feat, [FE], refactor

#260 feat : 프로젝트 작성 시 등록되는 랜덤이미지를 스프라이트화
  frontend/components/project/ProjectCard.tsx
  frontend/public/sprites/random_img_sprites.png
  frontend/styles/App.css
  frontend/styles/randomImg.css
Labels: feat, [FE], refactor

#261 fix : 사용 스택 표출 및 author 이동 문제
  frontend/components/common_box/AuthorBox.tsx
  frontend/pages/users/me/index.tsx
Labels: [FE], Fix

#265 Dev/fe
  frontend/components/Contact.tsx
  frontend/components/Filter.tsx
  frontend/components/answer/AnswerItem.tsx
  frontend/components/authAction/AuthContainer.tsx
  frontend/components/authAction/UserEditForm.tsx
  frontend/components/background/ModalBg.tsx
  frontend/components/common_box/MainArticleBox.tsx
  frontend/components/header/EtcHeader.tsx
  frontend/components/project/PeriodBox.tsx
  frontend/components/project/ProjectCard.tsx
  frontend/components/project/ProjectForm.tsx
  frontend/components/project/StacksBox.tsx
  frontend/components/project/TagBox.tsx
  frontend/components/user/LoginBg.tsx
  frontend/components/user/UserMeContentsBox.tsx
  frontend/components/user/UserPostCard.tsx
  frontend/pages/chat/[id].tsx
  frontend/pages/chat/create.tsx
  frontend/pages/chat/index.tsx
  frontend/pages/community/post/[id]/index.tsx
  frontend/pages/project/index.tsx
  frontend/pages/users/login/index.tsx
  frontend/pages/users/me/edit.tsx
  frontend/pages/users/me/index.tsx
  frontend/pages/users/signup/index.tsx
  frontend/styles/App.css
Labels: [FE], refactor
